### ISSUE TITLE
Breaking change between Atc.Cosmos v. 1.0.131 and 1.0.139

### ISSUE THREAD

**Issue by perkops** [atc-net/atc-cosmos#42]
After updating Atc.Cosmos package to v 1.0.139, the below error and therefore breaking change occurred when calling the following code:

```csharp
builder.Services.AddSingleton(s =>
{
    var options = s.GetRequiredService<IOptions<CosmosOptions>>().Value;

    return RuntimeInformation.IsOSPlatform(OSPlatform.OSX)
        ? new CosmosClient(options.AccountEndpoint, options.AccountKey, new CosmosClientOptions { ConnectionMode = ConnectionMode.Gateway })
        : new CosmosClient(options.AccountEndpoint, options.AccountKey);
});
```

Is this intended? Should versions be bumped instead?

Something needs to be added to the README so we know how to recover from this error.

```
System.AggregateException
  HResult=0x80131500
  Message=Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Atc.Cosmos.Internal.ICosmosContainerProvider Lifetime: Singleton ImplementationType: Atc.Cosmos.Internal.CosmosContainerProvider': Unable to resolve service for type 'Atc.Cosmos.Internal.ICosmosContainerRegistry' while attempting to activate 'Atc.Cosmos.Internal.CosmosContainerProvider'.) (Error while validating the service descriptor 'ServiceType: Atc.Cosmos.Internal.ICosmosInitializer Lifetime: Singleton ImplementationType: Atc.Cosmos.Internal.CosmosInitializer': Unable to resolve service for type 'Atc.Cosmos.Internal.ICosmosContainerRegistry' while attempting to activate 'Atc.Cosmos.Internal.CosmosInitializer'.) (Error while validating the service descriptor 'ServiceType: Atc.Cosmos.ICosmosReaderFactory Lifetime: Singleton ImplementationType: Atc.Cosmos.Internal.CosmosReaderFactory': Unable to resolve service for type 'Atc.Cosmos.Internal.ICosmosContainerRegistry' while attempting to activate 'Atc.Cosmos.Internal.CosmosContainerProvider'.) (Error while validating the service descriptor 'ServiceType: Atc.Cosmos.ICosmosWriterFactory Lifetime: Singleton ImplementationType: Atc.Cosmos.Internal.CosmosWriterFactory': Unable to resolve service for type 'Atc.Cosmos.Internal.ICosmosContainerRegistry' while attempting to activate 'Atc.Cosmos.Internal.CosmosContainerProvider'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: Atc.Cosmos.Internal.StartupInitializationJob': Unable to resolve service for type 'Atc.Cosmos.Internal.ICosmosContainerRegistry' while attempting to activate 'Atc.Cosmos.Internal.CosmosInitializer'.)
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in D:\Code\Api\Program.cs:line 71

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: Error while validating the service descriptor 'ServiceType: Atc.Cosmos.Internal.ICosmosContainerProvider Lifetime: Singleton ImplementationType: Atc.Cosmos.Internal.CosmosContainerProvider': Unable to resolve service for type 'Atc.Cosmos.Internal.ICosmosContainerRegistry' while attempting to activate 'Atc.Cosmos.Internal.CosmosContainerProvider'.

Inner Exception 2:
InvalidOperationException: Unable to resolve service for type 'Atc.Cosmos.Internal.ICosmosContainerRegistry' while attempting to activate 'Atc.Cosmos.Internal.CosmosContainerProvider'.```

**Comment by michaelskovslund** [comment]
I'll look into it.
